
atm-PRECIP = ""  # Do PREC_TOTAL = PRECC + PRECL
#atm-MAP_MEANANOM = "SST,PREC_TOTAL,ICEFRAC,LHFLX,SHFLX,PSL"
atm-MAP_MEANANOM = "TAUX,TAUY"
atm-HEAT_TRANSPORT = ""

ocn-REGRID = ""  # Regrid SST and HMXL
ocn-MAP_MEANANOM = "XMXL,TMXL"
